### ISSUE TITLE
user-defined distances method

### ISSUE THREAD

**Issue by josherrickson** [markmfredrickson/optmatch#174]
The scope of this issue has expanded to a general addressing of user-defined distances, accordingly I've updated the title. When this is wrapped up, the original description below can be opened into a new issue.

Original: A short vignette showing a user-defined distance calculation as the value passed to either `match_on.formula` or the `method` argument of `match_on.formula` would be handy.

**Comment by josherrickson** [comment]
Accidentally posted some follow-up to this in the wrong issue. Moving over here

---

I tried to write this up this morning and immediately ran into issues. One was addressed (see #180), but writing user-defined distances is still challenging.

The example in [`match_on`'s documentation](https://github.com/markmfredrickson/optmatch/blob/master/R/match_on.R#L519-L523) does not work:

```
> f <- function(index, data, z) {
+     abs(apply(index, 1, function(pair) {
+       data[pair[1]] - data[pair[2]]
+     }))
+   }
> fullmatch(pr ~ cost + t1, data = nuclearplants, method = "f")
 Error: $ operator is invalid for atomic vectors 
```

I believe the primary issue is that the example returns a vector, whereas the `mahalanobisHelper` function which our various `compute_*` functions calls returns an ISM (or `as.ISM`able) object which `match_on` expects. A user-defined function could probably return a matrix but it's not immediately obvious how to translate `index` and `data` into such a matrix appropriately without calling `match_on` again.

It seems to me that we could greatly simplify the API by doing most of the heavy lifting ourselves, and just have users define a function that takes in two points (vectors of equal length) and returns a distance between them.

-----

@benthestatistician's response:

> I agree that the proposed change would simplify the API, and be an
improvement in general. Would it simplify our lives to implement it,
however?

> If that's more than a small project, as I suspect it would be, then I'd
first ask for an assessment of what it would take to address this
particular bug.  I recall that it was @markmfredrickson who coded this up;
Mark could you squeeze in taking a look?  If not, and Josh has had enough
of this matter for the time being, I'll give it a whirl.

**Comment by markmfredrickson** [comment]
I've updated the docs by copying the version `match_on.numeric`. It seems the API got out of sync with the docs. Here's an example of it working:

```{r}
> f <- function(index, data, z) { abs(data[index[,1]] - data[index[,2]]) }
> xs <- rnorm(100) ; names(xs) <- 1:100
> z <- rbinom(100, size = 1, prob = 0.5)
> mm <- match_on(f, data = xs, z = z)
> mm[1:5, 1:5]
         control
treatment         2        3         4           7          8
       1  0.6210263 1.534561 0.8402249 0.204110900 1.34548555
       5  0.8233908 1.736926 1.0425894 0.001746361 1.14312101
       6  1.1353813 2.048916 1.3545799 0.310244151 0.83113049
       12 1.9230467 2.836582 2.1422454 1.097909580 0.04346507
       13 0.3739576 1.287492 0.5931562 0.451179601 1.59255425
```

**Comment by josherrickson** [comment]
There's still an issue here.

```
> f <- function(index, data, z) { abs(data[index[,1]] - data[index[,2]]) }
> xs <- rnorm(100) ; names(xs) <- 1:100
> z <- rbinom(100, size = 1, prob = 0.5)
> mm <- match_on(f, data = xs, z = z)
> mm[1:5, 1:5]
         control
treatment         1          2          3         6         7
       4  1.0729931 0.69129807 1.90403152 0.4579856 0.4746706
       5  2.8902856 1.12599434 0.08673911 1.3593068 2.2919630
       8  1.7015276 0.06276358 1.27549703 0.1705489 1.1032051
       10 1.6884738 0.07581746 1.28855091 0.1574950 1.0901512
       12 0.9153589 0.84893232 2.06166577 0.6156198 0.3170363
> 
> d <- data.frame(xs, z)
> mm <- match_on(z ~ xs, data = d, method = f)
> mm[1:5, 1:5]
         control
treatment  1  2  3  6  7
       4  NA NA NA NA NA
       5  NA NA NA NA NA
       8  NA NA NA NA NA
       10 NA NA NA NA NA
       12 NA NA NA NA NA
```

So `match_on.function` works fine with that custom function, `match_on.formula` with the `method` argument fails. 

Part of the issue is how the `data` argument to `match_on.function` and `match_on.formula` differ. In `match_on.formula`, the `data` argument is forced into a matrix ([match_on.r:346](https://github.com/markmfredrickson/optmatch/blob/master/R/match_on.R#L346)) before being passed to `makedist` (and subsequently the `f` function as defined above obviously indexes a matrix incorrectly and returns nonsense results). `match_on.function` has no such conversion and thus takes passes a vector to `makedist` and `f`.

While we could easily fix `f` to take a matrix `data` instead, or convert matrix to vector or vice-versa,, do end users need to worry about this? This is beginning to feel like a non-trivial problem; we need to first standardize between function and formula, then properly define the API (the easier part).

**Comment by benthestatistician** [comment]
One easy solution would be to only document/offer user-defined distance calcs together with `match_on.function()` (& not also `match_on.formula()`).  I think that may have been Mark's intention when he first wrote these things. Either way, an option to keep in mind as we consider solutions offering end users a route to providing distance computations for either one.

**Comment by benthestatistician** [comment]
Docs updates that will help:

1. In `match_on()` documentation, remove ", or pass a user created distance function"
2. Rephrase beginnings of paragraphs describing specific methods so that they (a) have a parallel structure and (b) make clear that it's the first argument / `x=` argument that determines which method is invoked. 
3. In the rare event that a user invokes `match_on.formula()` with a method argument other than one of ours, pass a warning to the effect that this isn't supported whereas `match_on.function()` does provide a mechanism for what they're trying to do.

**Comment by benthestatistician** [comment]
(I'm updating my last comment to reflect an additional suggestion arising after I just now went to the `match_on()` help page for info.  It really is difficult there to see where discussion of one method starts and discussion of the next method begins. Added material is 2c.)

**Comment by josherrickson** [comment]
I've made the changes we discussed above.
